---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ibot
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ibot
  filterTags:
    pattern: '\d+\.\d+\.\d+\-dev-.*'
  policy:
    semver:
      range: '>=0.0.0-dev-*'