apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibot
  namespace: ibot-dev
spec:
  selector:
    matchLabels:
      app: ibot
  chart:
    spec:
      chart: ./helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: ibot
  interval: 1m0s
  template:
    metadata:
      labels:
        app: ibot
    spec:
      containers:
        - name: ibot
          image: ghcr.io/k3ilona/ibot:0.1.3-dev-c473436 # {"$imagepolicy": "flux-system:ibot"}
          imagePullPolicy: IfNotPresent
