apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibot
  namespace: ibot-dev
spec:
  selector:
    matchLabels:
      app: ibot
  template:
    metadata:
      labels:
        app: ibot
    spec:
      containers:
        - name: ibot
          image: ghcr.io/k3ilona/ibot:0.1.4-dev-d4e1d8e-1706561827 # {"$imagepolicy": "flux-system:ibot"}
          imagePullPolicy: IfNotPresent
          env:
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ibot
                  key: appToken
            - name: SLACK_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ibot
                  key: token
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: ibot
                  key: channel-id
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
