---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ibot
  namespace: ibot-dev
spec:
  interval: 1m0s
  ref:
    branch: dev
  url: https://github.com/k3ilona/publisher-slack-bot.git